### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by koaning** [MBrouns/timeseers#13]
lemme know if you'd like me to fix one.

**Comment by MBrouns** [comment]
Oeh that'd be lovely :)

**Comment by koaning** [comment]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/1019791/79069123-ff339f80-7ccb-11ea-92fd-c325d584165e.png">

**Comment by MBrouns** [comment]
![image](https://user-images.githubusercontent.com/3510863/79079302-9d485980-7d0e-11ea-87f0-bcb056b79a54.png)

Thanks!
