### ISSUE TITLE
Settle on the API for hierarchical models

### ISSUE THREAD

**Issue by MBrouns** [MBrouns/timeseers#15]
```
# 1) class option
model = LinearTrend() + FourierSeasonality()
model = HierarchicalLinearTrend(group='subject') + FourierSeasonality()
model = GroupedLinearTrend(group='subject') + FourierSeasonality()

# 2) metaclass option
model = LinearTrend() + FourierSeasonality()
model = Hierarchical(LinearTrend(), on='subject') + FourierSeasonality()
model = Distinct(LinearTrend(), on='subject') + FourierSeasonality()

# 3) seperate hierarchy object 1
partial_subject = Share(type='partially_shared', on='subject')
distinct_subject = Share(type='distinct', on='subject')

model = LinearTrend() + FourierSeasonality()
model = LinearTrend().share(partial_subject) + FourierSeasonality()
model = LinearTrend().share(distinct_subject) + FourierSeasonality()

# 4) seperate hierarchy object 2
shared_subject = Share(type='shared')  # default
partial_subject = Share(type='partially_shared', on='subject')
distinct_subject = Share(type='distinct', on='subject')

model = LinearTrend(share=shared_subject) + FourierSeasonality(share=shared_subject)
model = LinearTrend(share=partial_subject) + FourierSeasonality()
model = LinearTrend(share=distinct_subject) + FourierSeasonality()

# 5) keyword option
model = LinearTrend(shared='full') + FourierSeasonality()  #  shared='full' is default
model = LinearTrend(group='subject', shared='partial') + FourierSeasonality()
model = LinearTrend(group='subject', shared='none') + FourierSeasonality()

# Cannibalism in this option
model = Constant(range=(0, None), shared='none') + LinearTrend(shared='full') + ((FourierSeasonality(perios=365) + FourierSeasonality(period=7)) * Constant(range=[-1, 1], group='subject', shared='none'))
model = LinearTrend() + (FourierSeasonality(perios=365) * Constant(range=[-1, 1], group='subject', shared='none')) + FourierSeasonality(period=7)

# 6) keyword option
model = LinearTrend() + FourierSeasonality()
model = LinearTrend(partially_shared_on='subject') + FourierSeasonality()
model = LinearTrend(distinct_on='subject') + FourierSeasonality()

# 7) bitwise or Operator option
model = LinearTrend()                                         # single estimation for all subjects
model = (LinearTrend() | 'subject') + FourierSeasonality()    # hierarchical estimation
model = (LinearTrend() || ('subject') + FourierSeasonality()  # independent estimation
```

#return day well spent

**Comment by MBrouns** [comment]
Current idea is to go for option 5. 1 and 2 seem like a hassle, 3 and 4 offer limited benefits, 6 mixes two things in the keyword argument and 7 is not self-explanatory and annoying with operator precedence

**Comment by koaning** [comment]
This discussion will go a lot smoother with an example. 

Let's say we're in retail. We've got a datasheet containing; `time`, `shop_id`, `region_id`, `product_id`, `prod_category_i`, `prod_category_ii`, `prod_category_iii`and `sales`.

We'd like to declare some models that should be reasonable. Here's a super simple one.

```python
df = read_csv(...)

model = Constant() + LinearTrend() + FourierSeasonality()
```

But now we say, "ah, but we'd like to do this per product". 

How's about? 

```python
model_per_product = model.per("product_id")
```

I don't know if this is a bit too "ruby"-style, we may prefer `group_by`. But it's better to have this discussion that has a tangible example. Anyway ... now folks might say "yeah but we need shrinkage on the season and constant". 

```python
model = (
    Constant().shrink_by("prod_category_i", 
                         "prod_category_ii", 
                         "prod_category_iii", 
                         "product_id") + 
    LinearTrend().group_by("product_id") + 
    FourierSeasonality().shrink_by("prod_category_i", 
                                   "prod_category_ii", 
                                   "prod_category_iii", 
                                   "product_id")
)
```

Now here's a fun grammar problem. What does it now mean if we do 

```python
model.groupby("product_id")
```

To me it feels like this should not be allowed. Only option 4/5/6 in your list guarantee this by API design. 

At the moment my preference goes out to option 4. That's mainly because the groups can get verbose in practice (check out the three categories and the id) so re-use is appreciated.

## Option 5

In this example you might get.

```python
product_share = Share(type="shrinkage", groups=["prod_category_i",
                                                "prod_category_ii", 
                                                "prod_category_iii", 
                                                "product_id"])
product_group = Share(type="discrete", groups=["product_id"])

model = (
    Constant(share=product_categories)
    LinearTrend().group_by("product_id") + 
    FourierSeasonality(share=product_categories)
)
```

I don't mind the idea that `share` is an optional variable in this case. It keeps the simple usecases simple. 

There's two more concerns though. 

- How would one declare groups combined with switchpoints? 
- How would one declare that the variance should be devided per group? Maybe the variance is not constant over time.

**Comment by MBrouns** [comment]
> Now here's a fun grammar problem. What does it now mean if we do `model.groupby("product_id")`

I agree that that probably shouldn't be allowed. I wonder if it's even worth setting this on the entire model, I expect in most cases that you shrink on some parameters but not on others.

> That's mainly because the groups can get verbose in practice (check out the three categories and the id) so re-use is appreciated.

True and that's indeed one of the major pros of option 4. That said though, you can also get that behaviour with `**kwargs` like this:

```
product_categories = {
    "type": "shrinkage",
    "groups": ["prod_category_i", "prod_category_ii"]
}

product_group = {
    "type": "distinct",
    "groups": "product_id"
}

model = (
    Constant(**product_group)
    LinearTrend(**product_categories) + 
    FourierSeasonality(**product_categories)
)
```
What do you mean with the combination with switchpoints? Variance is a good point. didn't really think about how that fits in the API yet at all.

**Comment by koaning** [comment]
> What do you mean with the combination with switchpoints? Variance is a good point. didn't really think about how that fits in the API yet at all.

You're gonna have switchpoints I assume here. So ... do you want to have switchpoints that you can group per type ... that can work. But shrinkage ... that should not be allowed I think. 

The `kwargs` approach works well enough for me.

**Comment by MBrouns** [comment]
suggestion:

call the paramers `pool_cols=[], pool_type={complete, partial, none}`

pool_type should be an enum;

Pooling.None
Pooling.Partial
Pooling.Complete

**Comment by koaning** [comment]
What does it mean if pooling is `partial`, `complete` or `None`?
