### ISSUE TITLE
Remove theano imports

### ISSUE THREAD

**Issue by MichalChromcak** [MBrouns/timeseers#26]
Hey,

I was browsing through the codebase and found it very interesting, considering playing a bit more with it. 

I saw then, that in some modules, there seems to be an unnecessary dependency on the `theano`.

https://github.com/MBrouns/timeseers/blob/50275a4f50eae9b7af0083b8db91d57b63684692/src/timeseers/constant.py#L6

No big issue, but more accessible if this would be removed while being quite a quick fix. What do you think?

**Comment by MBrouns** [comment]
This took way too long, but it's fixed in #32
