### ISSUE TITLE
Provide robustness to outliers

### ISSUE THREAD

**Issue by kori73** [MBrouns/timeseers#30]
Sometimes there is an unknown special effect that results in very high values in the time series. (let's say a hurricane). I might be okay not getting accurate predictions for those unknown special days. But the neighboring points might also be affected due to the  Fourier seasonality. I think it could be nice to provide a model that is robust to outliers. One approach could be adding an option to use `pm.StudentT` for the observations. 

PyMC3 docs has a nice example that includes other (more advanced) methods as well. [GLM: Robust Regression example](https://docs.pymc.io/notebooks/GLM-robust-with-outlier-detection.html#4.-Simple-Linear-Model-with-Robust-Student-T-Likelihood)

Here is a motivating example:

```
from timeseers.utils import seasonal_data
from timeseers import FourierSeasonality, LinearTrend
import numpy as np
import pandas as pd

np.random.seed(42)

df, _ = seasonal_data(5)

df.loc[630, "value"] = 100.
df.loc[631, "value"] = 100.
df.loc[632, "value"] = 100.
df.loc[633, "value"] = 100.

model = FourierSeasonality(n=5, period=pd.Timedelta(days=365)) + LinearTrend(n_changepoints=1)
model.fit(df[["t"]], df["value"], tune=2000, cores=1, chains=1)
model.plot_components(X_true=df, y_true=df['value'])
```

Using normal distribution I get the following predictions.

![image](https://user-images.githubusercontent.com/36677585/110223827-81bde280-7ece-11eb-936d-e5aa13f933ff.png)

Changing to StudentT (two line diff), I get:

![image](https://user-images.githubusercontent.com/36677585/110223846-a6b25580-7ece-11eb-960f-f97ec8cc1285.png)

Do you think this would be a useful addition to the library?

Afterthought:
There is a similar discussion on fbprophet too. See: [#1500](https://github.com/facebook/prophet/issues/1500).

It might be nice if the users could define the likelihood in `TimeSeriesModel` as they please.

**Comment by MBrouns** [comment]
Yes! I'd really like it if users could put in arbitrary likelihood terms somehow. One thing I've been toying with is how to get varying variance over time into the model. My current experiments work with specifying an additional time series model and using that as the variance for the first model, but it's proven difficult to sample and verify. 

An initial version could simply be allowing the user to specify the likelihood, like you said. Definitely open to it

**Comment by kori73** [comment]
It feels like there are a lot ways to provide such a mechanism. Maybe we can do something like fastai callbacks. Here is a rough version.

fit takes another argument (say callback)

```
class TimeSeriesModel(ABC):
    def fit(self, X, y, X_scaler=MinMaxScaler, y_scaler=StdScaler, callback=None, **sample_kwargs):
        if not X.index.is_monotonic_increasing:
            raise ValueError('index of X is not monotonically increasing. You might want to call `.reset_index()`')

        X_to_scale = X.select_dtypes(exclude='category')
        self._X_scaler_ = X_scaler()
        self._y_scaler_ = y_scaler()

        X_scaled = self._X_scaler_.fit_transform(X_to_scale)
        y_scaled = self._y_scaler_.fit_transform(y)
        model = pm.Model()
        X_scaled = X_scaled.join(X.select_dtypes('category'))
        del X
        mu = self.definition(
            model, X_scaled, self._X_scaler_.scale_factor_
        )
        if callback:
            callback.likelihood(self, model, mu, y_scaled, **sample_kwargs)
        else:
            with model:
                sigma = pm.HalfCauchy("sigma", 0.5)
                pm.Normal("obs", mu=mu, sd=sigma, observed=y_scaled)
                self.trace_ = pm.sample(**sample_kwargs)
```

The user writes a class (or a function?) that defines the custom likelihood.

```
import pymc3 as pm
class Robust():
    @staticmethod
    def likelihood(ts_model, model, mu, y_scaled, **sample_kwargs):
        with model:
            nu = pm.InverseGamma("nu", alpha=1, beta=1)
            sigma = pm.HalfCauchy("sigma", 0.5)
            pm.StudentT("obs", mu=mu, sd=sigma, nu=nu, observed=y_scaled)
            ts_model.trace_ = pm.sample(**sample_kwargs)
```
Then passes that class (or instance or function) to the fit method.

`model.fit(df[["t"]], df["value"], tune=2000, cores=1, chains=1, callback=Robust)
`
