### ISSUE TITLE
Does/can timeseers support external models for trend ?

### ISSUE THREAD

**Issue by akrishnamo** [MBrouns/timeseers#42]
Sorry for writing this question as an issue. One of the applications I deal with is forecasting short-mid life sku (2-10months). With prophet,  you cannot model the trend for the product lifecycle with introduction-growth-maturity-decline phases.  However, we can model trend with some kind of scikit/random forest type model based on other SKUs that have completed their lifecycle.

Is there any way to insert an external model for the trend component, for an application such as above?

**Comment by MBrouns** [comment]
Well the library definitely doesn't support it out of the box, but if you can parameterize it you can probably turn it into a component that you can include in your model definition.

I have to say the library is still quite rough at the moment, so you'll need to dig quite a bit to make it all work
